import { Annotation } from "@langchain/langgraph";

export const AgentState = Annotation.Root({
    taskId: Annotation(),
    task: Annotation(),
    goal: Annotation(),
    successCriteria: Annotation(),
    assumptions: Annotation(),
    taskKind: Annotation(),
    plan: Annotation(),
    memory: Annotation(),
    messages: Annotation(),
    latestSnapshot: Annotation(),
    pendingTool: Annotation(),
    lastObservation: Annotation(),
    stepCount: Annotation(),
    repeatHistory: Annotation(),
    nudgeCount: Annotation(),
    errorCount: Annotation(),
    evidenceCount: Annotation(),
    finishSummary: Annotation(),
    failure: Annotation(),
    warning: Annotation(),
    verificationRounds: Annotation(),
    status: Annotation(),
    result: Annotation(),
    trace: Annotation(),
});

export function createInitialState(taskId, task) {
    return {
        taskId,
        task,
        goal: "",
        successCriteria: [],
        assumptions: [],
        taskKind: "action",
        plan: [],
        memory: {},
        messages: [],
        latestSnapshot: null,
        pendingTool: null,
        lastObservation: null,
        stepCount: 0,
        repeatHistory: [],
        nudgeCount: 0,
        errorCount: 0,
        evidenceCount: 0,
        finishSummary: null,
        failure: null,
        warning: null,
        verificationRounds: 0,
        status: "running",
        result: null,
        trace: null,
    };
}
