import { Annotation } from "@langchain/langgraph";

export const AgentState = Annotation.Root({
    taskId: Annotation(),
    task: Annotation(),
    goal: Annotation(),
    successCriteria: Annotation(),
    assumptions: Annotation(),
    taskKind: Annotation(),
    plan: Annotation(),
    memory: Annotation(),
    messages: Annotation(),
    latestSnapshot: Annotation(),
    observationWindow: Annotation(),
    actionHistory: Annotation(),
    pendingTool: Annotation(),
    pendingInterrupt: Annotation(),
    lastObservation: Annotation(),
    stepCount: Annotation(),
    llmCallCount: Annotation(),
    repeatHistory: Annotation(),
    nudgeCount: Annotation(),
    errorCount: Annotation(),
    recoveryActive: Annotation(),
    llmRecoveryCalls: Annotation(),
    recoveryFailure: Annotation(),
    evidenceCount: Annotation(),
    finishSummary: Annotation(),
    failure: Annotation(),
    warning: Annotation(),
    verificationRounds: Annotation(),
    verification: Annotation(),
    hasAction: Annotation(),
    clarifications: Annotation(),
    status: Annotation(),
    result: Annotation(),
    trace: Annotation(),
});

export function createInitialState(taskId, task) {
    return {
        taskId,
        task,
        goal: "",
        successCriteria: [],
        assumptions: [],
        taskKind: "action",
        plan: [],
        memory: {},
        messages: [],
        latestSnapshot: null,
        observationWindow: {},
        actionHistory: [],
        pendingTool: null,
        pendingInterrupt: null,
        lastObservation: null,
        stepCount: 0,
        llmCallCount: 0,
        repeatHistory: [],
        nudgeCount: 0,
        errorCount: 0,
        recoveryActive: false,
        llmRecoveryCalls: 0,
        recoveryFailure: null,
        evidenceCount: 0,
        finishSummary: null,
        failure: null,
        warning: null,
        verificationRounds: 0,
        verification: null,
        hasAction: false,
        clarifications: [],
        status: "running",
        result: null,
        trace: null,
    };
}
